Models/People.cs
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcMovie.Models
{
    public class People
    {
        public int Id { get; set; }

        public string Firstname { get; set; }

        public string Surname { get; set; }

        public string City { get; set; }

        public string Country { get; set; }

        public string ProfilePic { get; set; }

        public string MobileNumber { get; set; }

        public string Gender { get; set; }

        public string Email { get; set; }
    }
}

Controllers/PeopleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MvcMovie.Data;
using MvcMovie.Models;
using Microsoft.AspNetCore.Http;

namespace MvcMovie.Controllers
{
    public class PeopleController : Controller
    {
        private readonly MvcPeopleContext _context;

        public PeopleController(MvcPeopleContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(string peopleCity, string peopleCountry, string searchString)
        {
            IQueryable<string> genreQueryCity = from m in _context.People
                orderby m.City
                select m.City;

            IQueryable<string> genreQueryCountry = from m in _context.People
                orderby m.Country
                select m.Country;

            var people = from m in _context.People
                select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                people = people.Where(s => s.Firstname.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(peopleCity))
            {
                people = people
                    .Where(x => x.City == peopleCity);
            }
            
            if (!string.IsNullOrEmpty(peopleCountry))
            {
                people = people
                    .Where(x => x.Country == peopleCountry);
            }

            var peopleCityCountryVm = new PeopleCityCountryViewModel
            {
                City = new SelectList(await genreQueryCity.Distinct().ToListAsync()),
                Country = new SelectList(await genreQueryCountry.Distinct().ToListAsync()),
                People = await people.ToListAsync()
            };

            return View(peopleCityCountryVm);
        }
        
        public async Task<IActionResult> Client(string peopleCity, string peopleCountry, string searchString)
        {
            IQueryable<string> genreQueryCity = from m in _context.People
                orderby m.City
                select m.City;

            IQueryable<string> genreQueryCountry = from m in _context.People
                orderby m.Country
                select m.Country;

            var people = from m in _context.People
                select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                people = people.Where(s => s.Firstname.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(peopleCity))
            {
                people = people
                    .Where(x => x.City == peopleCity);
            }
            
            if (!string.IsNullOrEmpty(peopleCountry))
            {
                people = people
                    .Where(x => x.Country == peopleCountry);
            }

            var peopleCityCountryVm = new PeopleCityCountryViewModel
            {
                City = new SelectList(await genreQueryCity.Distinct().ToListAsync()),
                Country = new SelectList(await genreQueryCountry.Distinct().ToListAsync()),
                People = await people.ToListAsync()
            };

            return View(peopleCityCountryVm);
        }

        public async Task<IActionResult> Admin(string peopleCity, string peopleCountry, string searchString)
        {
            IQueryable<string> genreQueryCity = from m in _context.People
                orderby m.City
                select m.City;

            IQueryable<string> genreQueryCountry = from m in _context.People
                orderby m.Country
                select m.Country;

            var people = from m in _context.People
                select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                people = people.Where(s => s.Firstname.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(peopleCity))
            {
                people = people
                    .Where(x => x.City == peopleCity);
            }
            
            if (!string.IsNullOrEmpty(peopleCountry))
            {
                people = people
                    .Where(x => x.Country == peopleCountry);
            }

            var peopleCityCountryVm = new PeopleCityCountryViewModel
            {
                City = new SelectList(await genreQueryCity.Distinct().ToListAsync()),
                Country = new SelectList(await genreQueryCountry.Distinct().ToListAsync()),
                People = await people.ToListAsync()
            };

            return View(peopleCityCountryVm);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var people = await _context.People
                .FirstOrDefaultAsync(m => m.Id == id);
            if (people == null)
            {
                return NotFound();
            }

            return View(people);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Firstname,Surname,City,Country,ProfilePic,MobileNumber,Gender,Email")]
            People people)
        {
            if (ModelState.IsValid)
            {
                _context.Add(people);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Admin));
            }

            return View(people);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var people = await _context.People.FindAsync(id);
            if (people == null)
            {
                return NotFound();
            }
            
            List<People> categorylist = new List<People>();

            categorylist = (from category in _context.People
                select category).ToList();

            categorylist.Insert(0, new People { Id = 0, Firstname = "Select" });

            ViewBag.ListofCategory = categorylist;

            return View(people);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,
            [Bind("Id,Firstname,Surname,Country,City,ProfilePic,MobileNumber,Gender,Email")]
            People people, People objcategory, IFormCollection formCollection)
        {

            List<People> categorylist = new List<People>();
            categorylist = (from category in _context.People
                select category).ToList();
            categorylist.Insert(0, new People { Id = 0, Country = "Select" });
            
            ViewBag.ListofCategory = categorylist;
            
            if (id != people.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(people);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_context.People.Any(e => e.Id == id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

                return RedirectToAction(nameof(Admin));
            }

            return View(people);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var people = await _context.People
                .FirstOrDefaultAsync(m => m.Id == id);
            if (people == null)
            {
                return NotFound();
            }

            return View(people);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var people = await _context.People.FindAsync(id);
            _context.People.Remove(people);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Admin));
        }

//        public JsonResult GetSubCategory(int CategoryID)
//        {
//            List<SubCategory> subCategorylist = new List<SubCategory>();
//
//            // ------- Getting Data from Database Using EntityFrameworkCore -------
//            subCategorylist = (from subcategory in _context.SubCategory
//                where subcategory.CategoryID == CategoryID
//                select subcategory).ToList();
//
//            // ------- Inserting Select Item in List -------
//            subCategorylist.Insert(0, new SubCategory { SubCategoryID = 0, SubCategoryName = "Select" });
//
//
//            return Json(new SelectList(subCategorylist, "SubCategoryID", "SubCategoryName"));
//        }
//
//        public JsonResult GetProducts(int SubCategoryID)
//        {
//            List<MainProduct> productList = new List<MainProduct>();
//
//            // ------- Getting Data from Database Using EntityFrameworkCore -------
//            productList = (from product in _context.MainProduct
//                where product.SubCategoryID == SubCategoryID
//                select product).ToList();
//
//            // ------- Inserting Select Item in List -------
//            productList.Insert(0, new MainProduct { ProductID = 0, ProductName = "Select" });
//
//            return Json(new SelectList(productList, "ProductID", "ProductName"));
//        }
    }
}

Views/People/Admin.cshtml
@model PeopleCityCountryViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "";
}

<h1>Admin Section</h1>

<li>
    <a href="/People/Client" class="elements">
        <span>Client Section</span>
    </a>
</li>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Index</title>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.8.10/themes/smoothness/jquery-ui.css" type="text/css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            $('#firstName').autocomplete({
                source: '/api/people/search'
            });
        });
    </script>
</head>
<body>


<form asp-controller="People" asp-action="Index" method="get">
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.People[0].City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.People[0].Country)
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <select asp-for="PeopleCity" asp-items="Model.City">
                    <option value="">All</option>
                </select>
            </td>
            <td>
                <select asp-for="PeopleCountry" asp-items="Model.Country">
                    <option value="">All</option>
                </select>
            </td>
        </tr>
        </tbody>
    </table>
    <br>
    <input type="text" id="firstName" placeholder="Firstname" asp-for="SearchString"/>
    <input type="submit" value="Filter"/>
</form>


<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.People[0].Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].MobileNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].Country)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.People)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<p>
    <a asp-action="Create">Create New</a>
</p>
</body>
</html>

Views/People/Client.cshtml
@model PeopleCityCountryViewModel

@{
    ViewData["Title"] = "Client Section";
    Layout = "";
}

<h1>Client Section</h1>

<li><a href="/People/Admin" class="elements"><span>Admin Section</span></a></li>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Index</title>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.8.10/themes/smoothness/jquery-ui.css" type="text/css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            $('#firstName').autocomplete({
                source: '/api/people/search'
            });
        });
    </script>
</head>
<body>



<form asp-controller="People" asp-action="Index" method="get">
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.People[0].City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.People[0].Country)
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <select asp-for="PeopleCity" asp-items="Model.City">
                    <option value="">All</option>
                </select>
            </td>
            <td>
                <select asp-for="PeopleCountry" asp-items="Model.Country">
                    <option value="">All</option>
                </select>
            </td>
        </tr>
        </tbody>
    </table>
    <br>
    <input type="text" id="firstName" placeholder="Firstname" asp-for="SearchString"/>
    <input type="submit" value="Filter"/>
</form>

</body>
</html>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.People[0].Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].MobileNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].Country)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.People)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
            </td>
        </tr>
    }
    </tbody>
</table>

Views/People/Create.cshtml
@model MvcMovie.Models.People

@{
    ViewData["Title"] = "Create";
    Layout = "";
}

<h1>Create</h1>

<h4>People</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Country" class="control-label"></label>
                <input asp-for="Country" class="form-control" />
                <span asp-validation-for="Country" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePic" class="control-label"></label>
                <input asp-for="ProfilePic" class="form-control" />
                <span asp-validation-for="ProfilePic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobileNumber" class="control-label"></label>
                <input asp-for="MobileNumber" class="form-control" />
                <span asp-validation-for="MobileNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control" />
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/People/Delete.cshtml
@model MvcMovie.Models.People

@{
    ViewData["Title"] = "Delete";
    Layout = "";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>People</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePic)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePic)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MobileNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MobileNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/People/Details.cshtml
@model MvcMovie.Models.People

@{
    ViewData["Title"] = "Details";

    Layout = "";
}

<h1>Details</h1>

<div>
    <h4>People</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Firstname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Firstname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Country)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Country)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePic)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProfilePic)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MobileNumber)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MobileNumber)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
    </dl>
</div>
<div>
    @* <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> | *@
    <a asp-action="Index">Back to List</a>
</div>

Views/People/Edit.cshtml
@model MvcMovie.Models.People

@{
    ViewData["Title"] = "Edit";
    Layout = "";
}

<script src="/lib/jquery/dist/jquery.js"></script>

<script type="text/javascript">
        $(document).ready(function () {
            var items = "<option value='0'>Select</option>";
            $('#SubCategoryID').html(items);
            $('#ProductID').html(items);
        });
</script>

<script type="text/javascript">  // not used yet. Intended to use for City AJAX
        $(document).ready(function () {
            $('#CategoryID').change(function () {
                var url = '@Url.Content("~/")' + "Demo/GetSubCategory";
                var ddlsource = "#CategoryID";
                $.getJSON(url, { CategoryID: $(ddlsource).val() }, function (data) {
                    var items = '';
                    $("#SubCategoryID").empty();
                    $.each(data, function (i, subcategory) {
                        items += "<option value='" + subcategory.value + "'>" + subcategory.text + "</option>";
                    });
                    $('#SubCategoryID').html(items);
                });
            });

            $('#SubCategoryID').change(function () {
                var url = '@Url.Content("~/")' + "Demo/GetProducts";
                var ddlsource = "#SubCategoryID";
                $.getJSON(url, { SubCategoryID: $(ddlsource).val() }, function (data) {
                    var items = '';
                    $('#ProductID').empty();
                    $.each(data, function (i, product) {
                        items += "<option value='" + product.value + "'>" + product.text + "</option>";
                    });
                    $('#ProductID').html(items);
                });
            });
        });
    </script>

<h1>Edit</h1>

<h4>People</h4>
<hr/>
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id"/>
            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control"/>
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control"/>
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                    <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4">
                        <label asp-for="Country" class="control-label"></label>
                        <select asp-for="Country" class="form-control"
                                asp-items="@(new SelectList(@ViewBag.ListofCategory, "Id", "Country"))">
                        </select>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control"/>
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePic" class="control-label"></label>
                <input asp-for="ProfilePic" class="form-control"/>
                <span asp-validation-for="ProfilePic" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MobileNumber" class="control-label"></label>
                <input asp-for="MobileNumber" class="form-control"/>
                <span asp-validation-for="MobileNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <input asp-for="Gender" class="form-control"/>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control"/>
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/People/Index.cshtml
 @model PeopleCityCountryViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "";
}

<h1>Client Section</h1>

<html>
<head>
    <meta name="viewport" content="width=device-width"/>
    <title>Index</title>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.8.10/themes/smoothness/jquery-ui.css" type="text/css">
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(document).ready(function () {
            $('#firstName').autocomplete({
                source: '/api/people/search'
            });
        });
    </script>
</head>
<body>

<form asp-controller="People" asp-action="Index" method="get">
    <table class="table">
        <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.People[0].City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.People[0].Country)
            </th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>
                <select asp-for="PeopleCity" asp-items="Model.City">
                    <option value="">All</option>
                </select>
            </td>
            <td>
                <select asp-for="PeopleCountry" asp-items="Model.Country">
                    <option value="">All</option>
                </select>
            </td>
        </tr>
        </tbody>
    </table>
    <br>
    <input type="text" id="firstName" placeholder="Firstname" asp-for="SearchString"/>
    <input type="submit" value="Filter"/>
</form>


@* <form asp-controller="People" asp-action="Index" method="get"> *@
@*     <p> *@
@*         <select asp-for="PeopleCity" asp-items="Model.City"> *@
@*             <option value="">All</option> *@
@*         </select> *@
@*         <select asp-for="PeopleCountry" asp-items="Model.Country"> *@
@*             <option value="">All</option> *@
@*         </select> *@
@*         <input type="text" id="firstName" placeholder="Firstname" asp-for="SearchString"/> *@
@*         $1$ Firstname: <input type="text" asp-for="SearchString"/> #1# *@
@*         <input type="submit" value="Filter"/> *@
@*     </p> *@
@* </form> *@

</body>
</html>

<table class="table">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.People[0].Firstname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].Surname)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].MobileNumber)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].City)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.People[0].Country)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.People)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Surname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.City)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Country)
            </td>
            <td>
                @* <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> | *@
                <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                @* <a asp-action="Delete" asp-route-id="@item.Id">Delete</a> *@
            </td>
        </tr>
    }
    </tbody>
</table>


@* <p> *@
@*     <a asp-action="Create">Create New</a> *@
@* </p> *@